// <copyright file="CSInteropTypes.Generated.cs" company="2018 Omar Tawfik">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

/// <summary>
/// This file is auto-generated by a build task. It shouldn't be edited by hand.
/// </summary>
namespace SuperBasic.Editor.Interop
{
    using System.Threading.Tasks;
    using Microsoft.JSInterop;

    internal interface IShapesInterop
    {
        Task<bool> NotifyButtonClicked(string buttonName);

        Task<bool> NotifyTextTyped(string textBoxName);
    }

    public static class CSInterop
    {
        private static readonly IShapesInterop Shapes = new ShapesInterop();

        [JSInvokable("CSIntrop.Shapes.NotifyButtonClicked")]
        public static async Task<bool> Shapes_NotifyButtonClicked(string buttonName)
            => await Shapes.NotifyButtonClicked(buttonName);

        [JSInvokable("CSIntrop.Shapes.NotifyTextTyped")]
        public static async Task<bool> Shapes_NotifyTextTyped(string textBoxName)
            => await Shapes.NotifyTextTyped(textBoxName);
    }
}
