// <copyright file="GenerateTokenKinds.cs" company="2018 Omar Tawfik">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

namespace SuperBasic.Generators.TokenKinds
{
    using System;
    using System.IO;
    using System.Linq;
    using SuperBasic.Utilities;

    public sealed class GenerateTokenKinds : BaseGeneratorTask
    {
        protected override void ExecuteConversion()
        {
            this.WriteFile<TokenKindsModels.TokenKindCollection>(
                inputFilePath: Path.Combine(this.RootDirectory, "Source", "SuperBasic.Generators", "TokenKinds", "Input.xml"),
                outputFilePath: Path.Combine(this.RootDirectory, "Source", "SuperBasic.Compiler", "Syntax", "Models", "TokenKind.Generated.cs"),
                converter: root =>
$@"// <copyright file=""TokenKind.Generated.cs"" company=""2018 Omar Tawfik"">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

/// <summary>
/// This file is auto-generated by a build task. It shouldn't be edited by hand.
/// </summary>
namespace SuperBasic.Compiler.Syntax
{{
    using SuperBasic.Utilities;
    using SuperBasic.Utilities.Resources;

    internal enum TokenKind
    {{
{root.Select(tokenKind => $"        {tokenKind.Name},").Join(Environment.NewLine)}
    }}

    internal static partial class TokenKindExtensions
    {{
        public static string ToDisplayString(this TokenKind kind)
        {{
            switch (kind)
            {{
{root.Select(tokenKind => $"                case TokenKind.{tokenKind.Name}: return {tokenKind.Display};").Join(Environment.NewLine)}
                default: throw ExceptionUtilities.UnexpectedValue(kind);
            }}
        }}
    }}
}}
");
        }
    }
}
