//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallBasic.Utilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmallBasic.Utilities.Resources.EditorResources", typeof(EditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Actions_Back {
            get {
                return ResourceManager.GetString("Actions_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will clear the existing program. Are you sure?.
        /// </summary>
        public static string Actions_ClearEverythingConfirmation {
            get {
                return ResourceManager.GetString("Actions_ClearEverythingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Actions_Continue {
            get {
                return ResourceManager.GetString("Actions_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Actions_Copy {
            get {
                return ResourceManager.GetString("Actions_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Actions_Cut {
            get {
                return ResourceManager.GetString("Actions_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Actions_Debug {
            get {
                return ResourceManager.GetString("Actions_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon!.
        /// </summary>
        public static string Actions_DisabledMessage_ComingSoon {
            get {
                return ResourceManager.GetString("Actions_DisabledMessage_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Actions_Import {
            get {
                return ResourceManager.GetString("Actions_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Actions_New {
            get {
                return ResourceManager.GetString("Actions_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Line.
        /// </summary>
        public static string Actions_NextLine {
            get {
                return ResourceManager.GetString("Actions_NextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Actions_Open {
            get {
                return ResourceManager.GetString("Actions_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Actions_Paste {
            get {
                return ResourceManager.GetString("Actions_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Actions_Pause {
            get {
                return ResourceManager.GetString("Actions_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Actions_Publish {
            get {
                return ResourceManager.GetString("Actions_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Actions_Redo {
            get {
                return ResourceManager.GetString("Actions_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Actions_Run {
            get {
                return ResourceManager.GetString("Actions_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Actions_Save {
            get {
                return ResourceManager.GetString("Actions_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Actions_Undo {
            get {
                return ResourceManager.GetString("Actions_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmallBasic.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Errors.
        /// </summary>
        public static string Errors_Count {
            get {
                return ResourceManager.GetString("Errors_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Errors_Description {
            get {
                return ResourceManager.GetString("Errors_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Errors_Line {
            get {
                return ResourceManager.GetString("Errors_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Header_DocumentationLink {
            get {
                return ResourceManager.GetString("Header_DocumentationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorials.
        /// </summary>
        public static string Header_TutorialsLink {
            get {
                return ResourceManager.GetString("Header_TutorialsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string LibraryExplorer_Events {
            get {
                return ResourceManager.GetString("LibraryExplorer_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string LibraryExplorer_Methods {
            get {
                return ResourceManager.GetString("LibraryExplorer_Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string LibraryExplorer_Properties {
            get {
                return ResourceManager.GetString("LibraryExplorer_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns nothing..
        /// </summary>
        public static string LibraryExplorer_ReturnsNothing {
            get {
                return ResourceManager.GetString("LibraryExplorer_ReturnsNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries.
        /// </summary>
        public static string LibraryExplorer_Title {
            get {
                return ResourceManager.GetString("LibraryExplorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Stack.
        /// </summary>
        public static string MemoryExplorer_CallStack {
            get {
                return ResourceManager.GetString("MemoryExplorer_CallStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string MemoryExplorer_Line {
            get {
                return ResourceManager.GetString("MemoryExplorer_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string MemoryExplorer_Module {
            get {
                return ResourceManager.GetString("MemoryExplorer_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MemoryExplorer_Name {
            get {
                return ResourceManager.GetString("MemoryExplorer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Ended.
        /// </summary>
        public static string MemoryExplorer_ProgramEnded {
            get {
                return ResourceManager.GetString("MemoryExplorer_ProgramEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Running.
        /// </summary>
        public static string MemoryExplorer_ProgramRunning {
            get {
                return ResourceManager.GetString("MemoryExplorer_ProgramRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string MemoryExplorer_Title {
            get {
                return ResourceManager.GetString("MemoryExplorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string MemoryExplorer_Value {
            get {
                return ResourceManager.GetString("MemoryExplorer_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string MemoryExplorer_Variables {
            get {
                return ResourceManager.GetString("MemoryExplorer_Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program has ended..
        /// </summary>
        public static string TextDisplay_TerminateMessage {
            get {
                return ResourceManager.GetString("TextDisplay_TerminateMessage", resourceCulture);
            }
        }
    }
}
