// <copyright file="GenerateDiagnosticBag.cs" company="2018 Omar Tawfik">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

namespace SuperBasic.Generators.Diagnostics
{
    using System;
    using System.IO;
    using System.Linq;
    using SuperBasic.Utilities;

    public sealed class GenerateDiagnosticBag : BaseGeneratorTask
    {
        protected override void ExecuteConversion()
        {
            this.WriteFile<DiagnosticsModels.DiagnosticsCollection>(
                inputFilePath: Path.Combine(this.RootDirectory, "Source", "SuperBasic.Generators", "Diagnostics", "Input.xml"),
                outputFilePath: Path.Combine(this.RootDirectory, "Source", "SuperBasic.Compiler", "Diagnostics", "DiagnosticBag.Generated.cs"),
                converter: root =>
$@"// <copyright file=""DiagnosticBag.Generated.cs"" company=""2018 Omar Tawfik"">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

/// <summary>
/// This file is auto-generated by a build task. It shouldn't be edited by hand.
/// </summary>
namespace SuperBasic.Compiler.Diagnostics
{{
    using System.Collections.Generic;
    using SuperBasic.Compiler.Syntax;
    using SuperBasic.Utilities;

    internal sealed class DiagnosticBag
    {{
        private readonly List<Diagnostic> builder = new List<Diagnostic>();

        public IReadOnlyList<Diagnostic> Contents => this.builder;
{root.Select(diagnostic => $@"
        public void Report{diagnostic.Name}(TextRange range{diagnostic.Parameters.Select(parameter => $", {parameter.Type} {parameter.Name}").Join(string.Empty)})
        {{
            this.builder.Add(new Diagnostic(DiagnosticCode.{diagnostic.Name}, range{diagnostic.Parameters.Select(parameter => $", {parameter.Name}.ToDisplayString()").Join(string.Empty)}));
        }}").Join(Environment.NewLine)}
    }}
}}
");
        }
    }
}
