// <copyright file="Bridge.Generated.cs" company="2018 Omar Tawfik">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

/// <summary>
/// This file is auto-generated by a build task. It shouldn't be edited by hand.
/// </summary>
namespace SuperBasic.Editor.Bridge
{
    using System.Threading.Tasks;
    using Microsoft.JSInterop;
    using SuperBasic.Utilities.Bridge;

    internal static class Bridge
    {
        public static class Test
        {
            public static async Task TestMethod1(string val1)
            {
                await JSRuntime.Current.InvokeAsync<bool>("Bridge.Test.TestMethod1", val1);
            }

            public static async Task<Bean1> TestMethod2()
            {
                return await JSRuntime.Current.InvokeAsync<Bean1>("Bridge.Test.TestMethod2");
            }

            public static async Task<string> TestMethod3()
            {
                return await JSRuntime.Current.InvokeAsync<string>("Bridge.Test.TestMethod3");
            }

            public static async Task<string> TestMethod4(Bean1 val4)
            {
                return await JSRuntime.Current.InvokeAsync<string>("Bridge.Test.TestMethod4", val4);
            }
        }
    }
}
