// <copyright file="BaseGeneratorTask.cs" company="2018 Omar Tawfik">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

namespace SuperBasic.Generators
{
    using System;
    using System.IO;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    using Microsoft.Build.Utilities;
    using SuperBasic.Utilities;

    public abstract class BaseGeneratorTask<TModel> : Task
    {
        public string Input { get; set; }

        public string Output { get; set; }

        private string Header =>
$@"// <copyright file=""{Path.GetFileName(this.Output)}"" company=""2018 Omar Tawfik"">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

/// <summary>
/// This file is auto-generated by a build task. It shouldn't be edited by hand.
/// </summary>";

        public sealed override bool Execute()
        {
            var settings = new XmlReaderSettings();
            settings.ValidationEventHandler += (sender, args) =>
            {
                switch (args.Severity)
                {
                    case XmlSeverityType.Error:
                        this.Log.LogError(args.Message);
                        break;
                    case XmlSeverityType.Warning:
                        this.Log.LogWarning(args.Message);
                        break;
                    default:
                        throw ExceptionUtilities.UnexpectedValue(args.Severity);
                }
            };

            using (var stream = new MemoryStream(File.ReadAllBytes(this.Input)))
            {
                using (var xmlReader = XmlReader.Create(stream, settings))
                {
                    var serializer = new XmlSerializer(typeof(TModel));
                    var model = (TModel)serializer.Deserialize(xmlReader);

                    File.WriteAllText(this.Output, this.Header + this.Convert(model));
                }
            }

            return !this.Log.HasLoggedErrors;
        }

        protected abstract string Convert(TModel model);
    }
}
