// <copyright file="CSInteropTypes.Generated.ts" company="2018 Omar Tawfik">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

/// <summary>
/// This file is auto-generated by a build task. It shouldn't be edited by hand.
/// </summary>

// Definition of this file is not published yet to somewhere we can consume. Declare for now:
// https://github.com/aspnet/Blazor/issues/1452
// https://github.com/aspnet/Blazor/blob/0.5.1/src/Microsoft.JSInterop/JavaScriptRuntime/src/Microsoft.JSInterop.ts
export declare module DotNet {
    function invokeMethodAsync<T>(assemblyName: string, methodIdentifier: string, ...args: any[]): Promise<T>;
}

export module CSIntrop {
    export module Shapes {
        export function notifyButtonClicked(buttonName: string): Promise<boolean> {
            return DotNet.invokeMethodAsync<boolean>("SuperBasic.Editor", "CSIntrop.Shapes.NotifyButtonClicked", buttonName);
        }

        export function notifyTextTyped(textBoxName: string): Promise<boolean> {
            return DotNet.invokeMethodAsync<boolean>("SuperBasic.Editor", "CSIntrop.Shapes.NotifyTextTyped", textBoxName);
        }
    }
}
