using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace SuperBasic.Compiler.Generators
{
    public class TokenKindEntry
    {
        [XmlAttribute]
        public string Name { get; set; }

        [XmlAttribute]
        public string Display { get; set; }
    }

    [XmlRoot("root")]
    public class TokenKindEntryList : List<TokenKindEntry>
    {
    }

    public class GenerateTokenKinds : BaseGeneratorTask<TokenKindEntryList>
    {
        protected override string GenerateDocumentContents(TokenKindEntryList model)
        {
            return
$@"// This file is auto-generated by a build task. It shouldn't be edited by hand.

using SuperBasic.Utilities;
using SuperBasic.Utilities.Resources;

namespace SuperBasic.Compiler.Generated
{{
    public enum TokenKind
    {{
{string.Join(Environment.NewLine, model.Select(item => $"        {item.Name},"))}
    }}

    public static partial class TokenKindExtensions
    {{
        public static string ToDisplayString(this TokenKind kind)
        {{
            switch (kind)
            {{
{string.Join(Environment.NewLine, model.Select(item => $"                case TokenKind.{item.Name}: return {item.Display};"))}
                default: throw ExceptionUtilities.UnexpectedValue(kind);
            }}
        }}
    }}
}}
";
        }
    }
}
