// <copyright file="TokenKind.Generated.cs" company="MIT License">
// Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

/// <summary>
/// This file is auto-generated by a build task. It shouldn't be edited by hand.
/// </summary>
namespace SmallBasic.Compiler.Scanning
{
    using SmallBasic.Utilities;
    using SmallBasic.Utilities.Resources;

    internal enum TokenKind
    {
        If,
        Then,
        Else,
        ElseIf,
        EndIf,
        For,
        To,
        Step,
        EndFor,
        While,
        EndWhile,
        Sub,
        EndSub,
        GoTo,
        Or,
        And,
        Dot,
        Comma,
        RightParen,
        LeftParen,
        RightBracket,
        LeftBracket,
        Equal,
        NotEqual,
        Plus,
        Minus,
        Multiply,
        Divide,
        Colon,
        LessThan,
        GreaterThan,
        LessThanOrEqual,
        GreaterThanOrEqual,
        Identifier,
        NumberLiteral,
        StringLiteral,
        Comment,
        Unrecognized,
    }

    internal static partial class TokenKindExtensions
    {
        public static string ToDisplayString(this TokenKind kind)
        {
            switch (kind)
            {
                case TokenKind.If: return "If";
                case TokenKind.Then: return "Then";
                case TokenKind.Else: return "Else";
                case TokenKind.ElseIf: return "ElseIf";
                case TokenKind.EndIf: return "EndIf";
                case TokenKind.For: return "For";
                case TokenKind.To: return "To";
                case TokenKind.Step: return "Step";
                case TokenKind.EndFor: return "EndFor";
                case TokenKind.While: return "While";
                case TokenKind.EndWhile: return "EndWhile";
                case TokenKind.Sub: return "Sub";
                case TokenKind.EndSub: return "EndSub";
                case TokenKind.GoTo: return "GoTo";
                case TokenKind.Or: return "Or";
                case TokenKind.And: return "And";
                case TokenKind.Dot: return ".";
                case TokenKind.Comma: return ",";
                case TokenKind.RightParen: return ")";
                case TokenKind.LeftParen: return "(";
                case TokenKind.RightBracket: return "]";
                case TokenKind.LeftBracket: return "[";
                case TokenKind.Equal: return "=";
                case TokenKind.NotEqual: return "<>";
                case TokenKind.Plus: return "+";
                case TokenKind.Minus: return "-";
                case TokenKind.Multiply: return "*";
                case TokenKind.Divide: return "/";
                case TokenKind.Colon: return ":";
                case TokenKind.LessThan: return "<";
                case TokenKind.GreaterThan: return ">";
                case TokenKind.LessThanOrEqual: return "<=";
                case TokenKind.GreaterThanOrEqual: return ">=";
                case TokenKind.Identifier: return TokenKindsResources.Identifier;
                case TokenKind.NumberLiteral: return TokenKindsResources.NumberLiteral;
                case TokenKind.StringLiteral: return TokenKindsResources.StringLiteral;
                case TokenKind.Comment: return TokenKindsResources.Comment;
                case TokenKind.Unrecognized: return TokenKindsResources.Unrecognized;
                default: throw ExceptionUtilities.UnexpectedValue(kind);
            }
        }
    }
}
