// <copyright file="BaseTask.cs" company="2018 Omar Tawfik">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

namespace SmallBasic.Generators
{
    using System;
    using System.IO;
    using System.Text;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    using SmallBasic.Utilities;

    public abstract class BaseTask
    {
        private readonly StringBuilder builder = new StringBuilder();

        private bool hasLoggedError = false;
        private bool braceLastAdded = false;
        private int indentationLevel = 0;

        protected int SaveAndExit(string filePath)
        {
            string result = this.builder.ToString();
            if (!File.Exists(filePath) || result != File.ReadAllText(filePath))
            {
                File.WriteAllText(filePath, result);
            }

            return this.hasLoggedError ? 1 : 0;
        }

        protected void LogError(string message)
        {
            Console.Error.WriteLine(message);
            this.hasLoggedError = true;
        }

        protected void Indent() => this.indentationLevel++;

        protected void Unindent() => this.indentationLevel--;

        protected void Brace()
        {
            this.Line("{");
            this.Indent();
        }

        protected void Unbrace()
        {
            this.braceLastAdded = false;
            this.Unindent();
            this.Line("}");
            this.braceLastAdded = true;
        }

        protected void Blank()
        {
            this.braceLastAdded = false;
            this.builder.AppendLine();
        }

        protected void Line(string line)
        {
            if (this.braceLastAdded)
            {
                this.builder.AppendLine();
                this.braceLastAdded = false;
            }

            this.builder.Append(' ', this.indentationLevel * 4);
            this.builder.AppendLine(line);
        }

        protected void GenerateDocHeader(string outputFile)
        {
            switch (Path.GetExtension(outputFile))
            {
                case ".cs":
                    {
                        this.Line($@"// <copyright file=""{Path.GetFileName(outputFile)}"" company=""2018 Omar Tawfik"">");
                        this.Line("// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.");
                        this.Line("// </copyright>");
                        break;
                    }

                case ".ts":
                    {
                        this.Line("/*!");
                        this.Line(" * Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.");
                        this.Line(" */");
                        break;
                    }

                case string other:
                    {
                        throw ExceptionUtilities.UnexpectedValue(other);
                    }
            }

            this.Blank();
            this.Line("/// <summary>");
            this.Line("/// This file is auto-generated by a build task. It shouldn't be edited by hand.");
            this.Line("/// </summary>");
        }
    }
}
