// <copyright file="Bridge.Generated.cs" company="2018 Omar Tawfik">
// Copyright (c) 2018 Omar Tawfik. All rights reserved. Licensed under the MIT License. See LICENSE file in the project root for license information.
// </copyright>

/// <summary>
/// This file is auto-generated by a build task. It shouldn't be edited by hand.
/// </summary>
namespace SuperBasic.Bridge
{
    using System.Diagnostics;
    using System.IO;
    using Newtonsoft.Json;
    using SuperBasic.Utilities;

    internal interface IProcessBridge
    {
        void OpenExternalLink(string url);
    }

    internal static class BridgeExecution
    {
        private static readonly IProcessBridge Process = new ProcessBridge();

        public static void Run(string[] args)
        {
            Debug.Assert(args.Length >= 2, "Only intended for bridge calls");

            string type = args[0];
            string method = args[1];
            string filePath = args.Length > 2 ? args[2] : null;

            switch (type)
            {
                case "Process":
                {
                    switch (method)
                    {
                        case "OpenExternalLink":
                        {
                            string input = JsonConvert.DeserializeObject<string>(File.ReadAllText(filePath));
                            Process.OpenExternalLink(input);
                            break;
                        }

                        default:
                        {
                            throw ExceptionUtilities.UnexpectedValue(method);
                        }
                    }

                    break;
                }

                default:
                {
                    throw ExceptionUtilities.UnexpectedValue(type);
                }
            }
        }
    }
}
