on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ["Debug", "Release"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.11.1
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1
      - run: npm install
        working-directory: ./Source/SmallBasic.Client
      - run: dotnet restore
      - run: dotnet build ./SmallBasic.sln /p:TreatWarningsAsErrors=True /p:Configuration=${{matrix.configuration}}
      - run: dotnet test ./Source/SmallBasic.Tests /p:Configuration=${{matrix.configuration}}
